image:
  file: .gitpod.dockerfile
tasks:
 - init: . ${GITPOD_REPO_ROOT}/.theia/init_tasks.sh    
vscode:
  extensions:
    - ms-python.python@2019.8.30787:TnGEOx35GXMhyKLjDGz9Aw==
    - formulahendry.auto-close-tag@0.5.9:JZIefALANqOfhSK1TU4+Fw==
    - mkaufman.HTMLHint@0.10.0:xevX4CvYOkKd8xjvtJQiGQ==
    - eventyret.bootstrap-4-cdn-snippet@1.9.0:I8wcXFcKWQIROg7J0SLLqg==
    - esbenp.prettier-vscode@5.7.1:4Zx39KyQMoIz7x94PSmDmQ==
    - kevinglasson.cornflakes-linter@0.5.1:KAaMshgHOKan8eojXQ53OQ==

    - hookyqr.beautify@1.4.11:9fd0c911415b603fd81da057c66fa963
    - dbaeumer.jshint@0.10.21:bf467ed793bc380b503b5f099140e27b